const product = [
    {
      id: 0,
      image: "imgs/amg.png",
      title: "Mersedes AMG",
      price: 120000,
    },
    {
      id: 1,
      image: "imgs/cad-cts.png",
      title: "Cadillac-CTS",
      price: 6000,
    },
    {
      id: 2,
      image: "imgs/camaro.png",
      title: "Chevrolet Camaro",
      price: 23000,
    },
    {
      id: 3,
      image: "imgs/dodge.jpg",
      title: "Dodge",
      price: 10000,
    },
    {
      id: 4,
      image: "imgs/duster.png",
      title: "Renault Duster",
      price: 2400,
    },
    {
      id: 5,
      image: "imgs/evo.png",
      title: "Mitsu Evolution",
      price: 100000,
    },
    {
      id: 6,
      image: "imgs/f150.png",
      title: "Ford F-150",
      price: 45000,
    },
    {
      id: 7,
      image: "imgs/focus-rs.jpg",
      title: "Ford Focus-RS",
      price: 57500,
    },
    {
      id: 8,
      image: "imgs/gtr.png",
      title: "Nissan GTR",
      price: 120000,
    },
    {
      id: 9,
      image: "imgs/Honda.png",
      title: "Honda S2000",
      price: 7800,
    },
    {
      id: 10,
      image: "imgs/i8.png",
      title: "BMW I8",
      price: 110000,
    },
    {
      id: 11,
      image: "imgs/matiz.jpg",
      title: "MATIZ",
      price: 80 ,
    },
    {
      id: 12,
      image: "imgs/mazda.png",
      title: "Mazda MX5",
      price: 9780,
    },
    {
      id: 13,
      image: "imgs/octaha.png",
      title: "Scoda Octavia",
      price: 1000,
    },
    {
      id: 14,
      image: "imgs/ram.png",
      title: "Dodge RAM",
      price: 10000,
    },
    {
      id: 15,
      image: "imgs/rs6.png",
      title: "Audi RS^",
      price: 54000,
    },
    {
      id: 16,
      image: "imgs/subaru.png",
      title: "Subaru",
      price: 30000,
    },
    {
      id: 17,
      image: "imgs/toyota.png",
      title: "Toyota",
      price: 5400,
    },
  ];